from math import *
help(ceil)
print('\t example of ceil:',ceil(10.5))
print('\t factorial:',factorial(10))
print('\n \t e:',e,'\n \t pi:',pi)
print('\t sqrt:',sqrt(4))
help(fabs)
print('\t fabs:',fabs(-103.322))
print('\t fabs:',fabs(103.22))
print('\t floor:',(floor(10.5)))
r=int(input('enter radius:' ))
area=pi*pow(r,2) #pow:-power of the arguments here r²
print('\t area of the circle:',area)
a=float(input('enter a:'))
print(floor(fabs(a)))
